---
abstract: 'A Perl interface to the Unicorn webserver'
author:
  - 'Mugen Kenichi <mugen.kenichi@uninets.eu>'
build_requires:
  Module::Build: 0.38
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.112621'
license: mit
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Unicorn-Manager
no_index:
  directory:
    - t
provides:
  Unicorn::Manager:
    file: lib/Unicorn/Manager.pm
    version: 0.005003
  Unicorn::Manager::Proc:
    file: lib/Unicorn/Manager/Proc.pm
    version: 0.005003
  Unicorn::Manager::Proc::Table:
    file: lib/Unicorn/Manager/Proc.pm
    version: 0
  Unicorn::Manager::Types:
    file: lib/Unicorn/Manager/Types.pm
    version: 0.005003
  Unicorn::Manager::Version:
    file: lib/Unicorn/Manager/Version.pm
    version: 0.005003
requires:
  B::Hooks::OP::Check: 0.19
  Carp: 0
  Cwd: 0
  File::Basename: 0
  Getopt::Long: 0
  JSON: 0
  Moo: 0
  Test::More: 0
  Time::HiRes: 0
  YAML: 0
  bareword::filehandles: 0
  indirect: 0
  multidimensional: 0
resources:
  license: http://opensource.org/licenses/mit-license.php
version: 0.005003
